# -*- coding: utf-8 -*-
"""tugas2_2611531005.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MVdsWnys4b4QDh_sN4KM52TtueTh8vpH
"""

print ("=== SISTEM REGISTRASI PRAKTIKAN ALPRO 2026 ===")

nama_1005 = input(str("Masukkan Nama Mahasiswa : "))
jenis_kelamin_1005 = input ("Masukkan Jenis Kelamin (L/P) : ")
umur_1005 = int(input("Masukkan Umur : "))
skor_tes_awal_1005 = float(input("Masukkan Skor Tes Awal : ").replace(',', '.'))

print("\n=== DATA PRAKTIKAN & HASIL PEMERIKSAAN ===")

alamat_1005 = """
Andalas Residance,
Limau Manis, Kecamatan Pauh, Kota Padang, Sumatera Barat, Indonesia ,
Kota Padang """
id_token_sinyal = 100+3j

print("Nama Mahasiswa :", nama_1005, "|", "Tipe :", type(nama_1005))
print("Jenis Kelamin :", jenis_kelamin_1005, "|", "Tipe :", type(jenis_kelamin_1005))
print("Alamat Domisili :", alamat_1005, "|", "Tipe :", type(alamat_1005))
print("Umur :", umur_1005, "tahun", "|", "Tipe :", type(umur_1005))
print("Skor Tes Awal :", skor_tes_awal_1005, "|", "Tipe :", type (skor_tes_awal_1005))
print("ID Token Sinyal :", id_token_sinyal, "|", "Tipe :", type (id_token_sinyal))

print("\n=== STATUS KELULUSAN PRAKTIKUM ===")

batas_1005 = 75.0

print("Batas Minimum Nilai:", batas_1005)
if skor_tes_awal_1005 >= batas_1005:
    hasil_1005 = True
else:
    hasil_1005 = False
print("Apakah dinyatakan lulus?:", hasil_1005, "|", "Tipe :", type (hasil_1005))