# -*- coding: utf-8 -*-
"""tugas4_2611531005.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wEFzBlDHuK2PaVKWzi8GkW4UKulq9drp
"""

print("=== SISTEM LOKET ALPRO ADVENTURE PARK ===")

# 1. Input Data Pengunjung Utama
nama_1005 = input("Masukkan Nama Pengunjung        : ")
umur_1005 = int(input("Input umur anda                 : "))
sim_1005 = input("Apakah Anda Sudah Punya SIM C (y/t): ")[0].lower()

# Status Kepemilikan SIM
status_sim_1005 = "Punya" if sim_1005 == 'y' else "Tidak Punya"

#Output biodata pengunjung
print("\n-----------------------------------------")
print("--- BIODATA PENGUNJUNG ---")
print(f"Nama Pengunjung  : {nama_1005}")
print(f"Umur             : {umur_1005} tahun")
print(f"Status SIM C     : {status_sim_1005}")

# Tampilkan Daftar Paket Wahana untuk Masukan Pengunjung
print("\nPilihan Paket Wahana (1-5):")
print("  1. Safari Rimba         (Rp 50,000)")
print("  2. Arung Jeram          (Rp 75,000)")
print("  3. Motor ATV Ekstrim    (Rp 120,000)")
print("  4. Roller Coaster Kilat (Rp 100,000)")
print("  5. All-Access VIP       (Rp 220,000)")

paket_1005 = int(input("Masukkan nomor paket (1-5)      : "))
jumlah_tiket_1005 = int(input("Masukkan jumlah tiket           : "))

# Penerapan IF tunggal untuk validasi kuota tiket
if jumlah_tiket_1005 <= 0:
    print("Peringatan: Kuota tiket tidak valid!")

input_member_1005 = input("Apakah Anda member? (y/t)        : ").strip().lower()
is_member_1005 = input_member_1005 in [ "y", "ya"]

input_promo_1005 = input("Apakah kode promo valid? (y/t)  : ").strip().lower()
kode_promo_valid_1005 = input_promo_1005 in [ "y", "ya"]

# 2. Pemilihan Wahana Menggunakan match-case
harga_satuan_1005 = 0
nama_wahana_1005 = ""

match paket_1005:
    case 1:
        nama_wahana_1005 = "Wahana Safari Rimba"
        harga_satuan_1005 = 50000
    case 2:
        nama_wahana_1005 = "Wahana Arung Jeram"
        harga_satuan_1005 = 75000
    case 3:
        nama_wahana_1005 = "Wahana Motor ATV Ekstrim"
        harga_satuan_1005 = 120000
    case 4:
        nama_wahana_1005 = "Wahana Roller Coaster Kilat"
        harga_satuan_1005 = 100000
    case 5:
        nama_wahana_1005 = "Wahana All-Access VIP"
        harga_satuan_1005 = 220000
    case _:
        print("\nPaket wahana tidak valid!")
        harga_satuan_1005 = 0


# 3. Validasi Izin Kendali Wahana Menggunakan if-elif-else
print("\n--- KELAYAKAN PENGENDARA WAHANA ---")
if paket_1005 == 3:
       if umur_1005 >= 17 and sim_1005 == 'y':
           status_akses_1005 = "Anda sudah dewasa dan boleh mengendarai ATV sendiri."
       elif umur_1005 >= 17 and sim_1005 != 'y':
           status_akses_1005 = "Anda sudah dewasa tetapi tidak boleh bawa motor ATV (wajib didampingi instruktur)."
       elif umur_1005 < 17 and sim_1005 == 'y':
           status_akses_1005 = "Identitas tidak valid: Belum cukup umur memiliki SIM."
       else:
           status_akses_1005 = "Anda belum cukup umur dan tidak boleh bawa motor ATV."
else:
       if umur_1005 >= 10:
           status_akses_1005 = "Anda memenuhi syarat umur untuk wahana ini."
       else:
           status_akses_1005 = "Anda belum cukup umur untuk wahana ini."

print(f"Status Akses: {status_akses_1005}")

    # 4. Akumulasi Diskon Bertingkat Menggunakan Multi-IF Terpisah
subtotal_1005 = harga_satuan_1005 * jumlah_tiket_1005
total_diskon_persen_1005 = 0

if subtotal_1005 >= 200000:
        total_diskon_persen_1005 += 10  # Diskon Belanja Besar

if is_member_1005:
        total_diskon_persen_1005 += 5   # Diskon Member

if kode_promo_valid_1005:
        total_diskon_persen_1005 += 15  # Diskon Voucher Promo

if jumlah_tiket_1005 >= 5:
        total_diskon_persen_1005 += 5   # Diskon Tambahan Rombongan

    # 5. Menghitung Nominal Diskon dan Total Bayar
nominal_diskon_1005 = subtotal_1005 * (total_diskon_persen_1005 / 100)
total_bayar_1005 = subtotal_1005 - nominal_diskon_1005

    # Evaluasi Bonus Audit Menggunakan if-else
if total_bayar_1005 > 300000:
        catatan_layanan_1005 = "Selamat! Anda berhak mendapatkan Souvenir Gratis."
else:
        catatan_layanan_1005 = "Terima kasih telah berkunjung."

    # OUTPUT SELANJUTNYA: RINCIAN PEMBAYARAN
print("\n--- RINCIAN PEMBAYARAN ---")
print(f"Paket Dipilih    : Paket {paket_1005} ({nama_wahana_1005})")
print(f"Jumlah Tiket     : {jumlah_tiket_1005} tiket")
print(f"Status Member    : {input_member_1005}")
print(f"Kode Promo Valid : {input_promo_1005}")
print(f"Wahana Dipilih   : {nama_wahana_1005}")
print(f"Jumlah Tiket     : {jumlah_tiket_1005} tiket")
print(f"Subtotal Belanja : Rp {subtotal_1005:,.0f}")
print(f"Total Diskon     : {total_diskon_persen_1005}% (Rp {nominal_diskon_1005:,.0f})")
print(f"Total Bayar      : Rp {total_bayar_1005:,.0f}")
print(f"Catatan Layanan  : {catatan_layanan_1005}")

print("Program Selesai")